import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart' as intl;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../services/theme_service.dart';

class TripDetailModal extends StatelessWidget {
  final Map<String, dynamic> trip;
  final VoidCallback onDelete;

  const TripDetailModal({
    super.key,
    required this.trip,
    required this.onDelete,
  });

  int _countRealAlerts(dynamic alertsData) {
    try {
      if (alertsData == null) return 0;
      String s = alertsData.toString();
      if (s == "[]" || s.isEmpty) return 0;
      List<dynamic> list = json.decode(s);
      int count = 0;
      for (var item in list) {
        String event = item.toString().toLowerCase();
        if (event.contains('drowsy') ||
            event.contains('manual') ||
            event.contains('sos') ||
            event.contains('danger')) {
          count++;
        }
      }
      return count;
    } catch (_) {
      return 0;
    }
  }

  List<Map<String, dynamic>> _parseAlerts() {
    try {
      if (trip['alerts'] == null) return [];
      if (trip['alerts'] is String) {
        List<dynamic> list = json.decode(trip['alerts']);
        List<Map<String, dynamic>> parsed = [];

        for (var e in list) {
          String raw = e.toString();
          String lower = raw.toLowerCase();

          if (lower.contains('trip started') || lower.contains('trip ended'))
            continue;

          String type = 'Drowsiness Detected';
          String severity = 'high';

          if (lower.contains('manual') ||
              lower.contains('sos') ||
              lower.contains('emergency')) {
            type = 'Emergency Alert';
          }

          parsed.add({
            'time': raw.contains('T')
                ? raw.split('T').last.substring(0, 5)
                : '00:00',
            'type': type,
            'severity': severity,
          });
        }
        return parsed;
      }
    } catch (_) {
      return [];
    }
    return [];
  }

  Future<void> _generateAndSharePdf(BuildContext context) async {
    final pdf = pw.Document();
    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Text(
                  "Trip Report - Yaqdah",
                  style: pw.TextStyle(
                    fontSize: 24,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
              ),
              pw.SizedBox(height: 20),
              pw.Text("Date: ${trip['date']}"),
              pw.Text("Duration: ${trip['duration']}"),
              pw.Text("Distance: ${trip['distance']}"),
              pw.Text("Status: ${trip['status']}"),
              pw.Divider(),
              pw.Text(
                "Alerts Log:",
                style: pw.TextStyle(
                  fontSize: 18,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 10),
              ..._parseAlerts().map(
                (a) => pw.Bullet(
                  text: "${a['time']} - ${a['type']} (${a['severity']})",
                ),
              ),
              pw.Spacer(),
              pw.Text("Generated by Yaqdah App"),
            ],
          );
        },
      ),
    );
    await Printing.sharePdf(
      bytes: await pdf.save(),
      filename: 'trip_report_${trip['id']}.pdf',
    );
  }

  @override
  Widget build(BuildContext context) {
    // ✅ Dynamic Theme
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;
    final textColor = theme.textTheme.bodyMedium!.color;
    final subColor = isDark ? Colors.grey[400] : Colors.grey[600];
    final borderColor = theme.dividerColor;
    final green = theme.primaryColor;
    final orange = ThemeService.orange;
    final red = ThemeService.red;

    int alertsCount = _countRealAlerts(trip['alerts']);
    String statusStr = trip['status'].toString().toLowerCase();

    final bool isSafe =
        (alertsCount == 0) &&
        !statusStr.contains('drowsy') &&
        !statusStr.contains('danger');
    final alerts = _parseAlerts();

    return DraggableScrollableSheet(
      initialChildSize: 0.85,
      minChildSize: 0.5,
      maxChildSize: 0.95,
      builder: (_, controller) {
        return Container(
          decoration: BoxDecoration(
            color: theme.scaffoldBackgroundColor, // ✅ Dynamic BG
            borderRadius: const BorderRadius.vertical(top: Radius.circular(30)),
          ),
          child: Column(
            children: [
              // Header
              Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  border: Border(bottom: BorderSide(color: borderColor)),
                ),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Row(
                      children: [
                        Container(
                          padding: const EdgeInsets.all(10),
                          decoration: BoxDecoration(
                            color: isSafe
                                ? green.withOpacity(0.2)
                                : orange.withOpacity(0.2),
                            borderRadius: BorderRadius.circular(12),
                            border: Border.all(color: isSafe ? green : orange),
                          ),
                          child: Icon(
                            isSafe ? Icons.check_circle : Icons.warning,
                            color: isSafe ? green : orange,
                          ),
                        ),
                        const SizedBox(width: 12),
                        Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              "Trip Details",
                              style: TextStyle(
                                color: textColor,
                                fontWeight: FontWeight.bold,
                                fontSize: 16,
                              ),
                            ),
                            Text(
                              intl.DateFormat(
                                'yyyy-MM-dd',
                              ).format(DateTime.parse(trip['date'])),
                              style: TextStyle(color: subColor, fontSize: 12),
                            ),
                          ],
                        ),
                      ],
                    ),
                    IconButton(
                      icon: Icon(Icons.close, color: subColor),
                      onPressed: () => Navigator.pop(context),
                    ),
                  ],
                ),
              ),

              // Scrollable Content
              Expanded(
                child: ListView(
                  controller: controller,
                  padding: const EdgeInsets.all(20),
                  children: [
                    Center(
                      child: Container(
                        padding: const EdgeInsets.symmetric(
                          horizontal: 24,
                          vertical: 12,
                        ),
                        decoration: BoxDecoration(
                          color: isSafe
                              ? green.withOpacity(0.2)
                              : orange.withOpacity(0.2),
                          borderRadius: BorderRadius.circular(30),
                          border: Border.all(color: isSafe ? green : orange),
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            Icon(
                              isSafe ? Icons.check_circle : Icons.warning,
                              size: 20,
                              color: isSafe ? green : orange,
                            ),
                            const SizedBox(width: 8),
                            Text(
                              isSafe ? "Safe Trip" : "Drowsiness Detected",
                              style: TextStyle(
                                color: isSafe ? green : orange,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    const SizedBox(height: 24),

                    GridView.count(
                      crossAxisCount: 2,
                      shrinkWrap: true,
                      physics: const NeverScrollableScrollPhysics(),
                      crossAxisSpacing: 12,
                      mainAxisSpacing: 12,
                      childAspectRatio: 1.5,
                      children: [
                        _gridItem(
                          "Duration",
                          trip['duration'] ?? "00:00:00",
                          Icons.access_time,
                          ThemeService.purple,
                          theme,
                          textColor!,
                        ),
                        _gridItem(
                          "Distance",
                          trip['distance'] ?? "0.0 km",
                          Icons.map,
                          ThemeService.blue,
                          theme,
                          textColor,
                        ),
                        _gridItem(
                          "Avg Speed",
                          trip['avgSpeed'] ?? "0.0 km/h",
                          Icons.speed,
                          green,
                          theme,
                          textColor,
                        ),
                        _gridItem(
                          "Alerts",
                          "$alertsCount",
                          Icons.warning_amber,
                          orange,
                          theme,
                          textColor,
                        ),
                      ],
                    ),
                    const SizedBox(height: 24),

                    Container(
                      padding: const EdgeInsets.all(16),
                      decoration: BoxDecoration(
                        color: theme.cardColor,
                        borderRadius: BorderRadius.circular(20),
                        border: Border.all(color: borderColor),
                      ),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Row(
                            children: [
                              Icon(
                                Icons.calendar_month,
                                color: green,
                                size: 16,
                              ),
                              const SizedBox(width: 8),
                              Text(
                                "Timeline",
                                style: TextStyle(
                                  color: textColor,
                                  fontWeight: FontWeight.bold,
                                ),
                              ),
                            ],
                          ),
                          const SizedBox(height: 16),
                          _timelineRow(
                            "Start Time",
                            trip['startTime'] ?? "--:--",
                            textColor,
                            subColor!,
                          ),
                          _timelineRow(
                            "End Time",
                            trip['endTime'] ?? "--:--",
                            textColor,
                            subColor,
                          ),
                          Divider(color: borderColor, height: 20),
                          _timelineRow(
                            "Max Speed",
                            trip['maxSpeed'] ?? "0.0 km/h",
                            textColor,
                            subColor,
                          ),
                        ],
                      ),
                    ),
                    const SizedBox(height: 24),

                    if (alerts.isNotEmpty) ...[
                      Container(
                        padding: const EdgeInsets.all(16),
                        decoration: BoxDecoration(
                          color: theme.cardColor,
                          borderRadius: BorderRadius.circular(20),
                          border: Border.all(color: borderColor),
                        ),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Row(
                              children: [
                                Icon(
                                  Icons.remove_red_eye,
                                  color: orange,
                                  size: 16,
                                ),
                                const SizedBox(width: 8),
                                Text(
                                  "Alerts Log",
                                  style: TextStyle(
                                    color: textColor,
                                    fontWeight: FontWeight.bold,
                                  ),
                                ),
                              ],
                            ),
                            const SizedBox(height: 16),
                            ...alerts.map(
                              (a) => Container(
                                margin: const EdgeInsets.only(bottom: 10),
                                padding: const EdgeInsets.all(12),
                                decoration: BoxDecoration(
                                  color: theme.scaffoldBackgroundColor,
                                  borderRadius: BorderRadius.circular(12),
                                  border: Border.all(color: borderColor),
                                ),
                                child: Row(
                                  children: [
                                    CircleAvatar(
                                      radius: 4,
                                      backgroundColor: red,
                                    ),
                                    const SizedBox(width: 12),
                                    Expanded(
                                      child: Column(
                                        crossAxisAlignment:
                                            CrossAxisAlignment.start,
                                        children: [
                                          Text(
                                            a['type'],
                                            style: TextStyle(
                                              color: textColor,
                                              fontSize: 14,
                                            ),
                                          ),
                                          Text(
                                            a['time'],
                                            style: TextStyle(
                                              color: subColor,
                                              fontSize: 12,
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 24),
                    ],

                    SizedBox(
                      width: double.infinity,
                      child: ElevatedButton.icon(
                        onPressed: () => _generateAndSharePdf(context),
                        icon: const Icon(Icons.download, color: Colors.black),
                        label: const Text(
                          "Download PDF Report",
                          style: TextStyle(
                            color: Colors.black,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                        style: ElevatedButton.styleFrom(
                          backgroundColor: green,
                          padding: const EdgeInsets.symmetric(vertical: 16),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(16),
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(height: 12),

                    SizedBox(
                      width: double.infinity,
                      child: TextButton.icon(
                        onPressed: () {
                          showDialog(
                            context: context,
                            builder: (ctx) => AlertDialog(
                              backgroundColor: theme.cardColor,
                              title: Text(
                                "Delete Report?",
                                style: TextStyle(color: textColor),
                              ),
                              content: const Text(
                                "Are you sure you want to delete this trip report?",
                                style: TextStyle(color: Colors.grey),
                              ),
                              actions: [
                                TextButton(
                                  onPressed: () => Navigator.pop(ctx),
                                  child: const Text(
                                    "Cancel",
                                    style: TextStyle(color: Colors.grey),
                                  ),
                                ),
                                TextButton(
                                  onPressed: () {
                                    Navigator.pop(ctx);
                                    onDelete();
                                  },
                                  child: const Text(
                                    "Delete",
                                    style: TextStyle(color: ThemeService.red),
                                  ),
                                ),
                              ],
                            ),
                          );
                        },
                        icon: const Icon(Icons.delete, color: ThemeService.red),
                        label: const Text(
                          "Delete Report",
                          style: TextStyle(
                            color: ThemeService.red,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                        style: TextButton.styleFrom(
                          padding: const EdgeInsets.symmetric(vertical: 16),
                        ),
                      ),
                    ),
                    const SizedBox(height: 20),
                  ],
                ),
              ),
            ],
          ),
        );
      },
    );
  }

  Widget _gridItem(
    String label,
    String value,
    IconData icon,
    Color color,
    ThemeData theme,
    Color textColor,
  ) {
    final borderColor = theme.dividerColor;
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: theme.cardColor,
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: borderColor),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Icon(icon, size: 18, color: color),
              const SizedBox(width: 8),
              Text(
                label,
                style: const TextStyle(color: Colors.grey, fontSize: 12),
              ),
            ],
          ),
          const Spacer(),
          Text(
            value,
            style: TextStyle(
              color: textColor,
              fontSize: 18,
              fontWeight: FontWeight.bold,
            ),
          ),
        ],
      ),
    );
  }

  Widget _timelineRow(
    String label,
    String val,
    Color textColor,
    Color subColor,
  ) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8.0),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(label, style: TextStyle(color: subColor)),
          Text(
            val,
            style: TextStyle(color: textColor, fontWeight: FontWeight.bold),
          ),
        ],
      ),
    );
  }
}
